name: Build Test Deploy Java App to Azure Container Apps

on:
  workflow_dispatch:

env: 
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/java-container-app
  RESOURCE_GROUP: java-container-rg-maryam
  CONTAINERAPP_NAME: java-container-app-maryam

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build & Test with Maven
        run: mvn clean test package

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            -n ${{ env.CONTAINERAPP_NAME }} \
            -g ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.IMAGE_NAME }}:${{ github.sha }}
